publish:
  whoami: asf-site

jekyll:
  whoami: main
  target: asf-site

notifications:
  commits:      commits@hive.apache.org
  issues:       gitbox@hive.apache.org
  pullrequests: gitbox@hive.apache.org
  jira_options: link label worklog
